# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'failed'), (1, 'pending'), (2, 'succeeded')], editable=False, verbose_name='status')),
                ('amount', models.PositiveIntegerField(editable=False, verbose_name='amount')),
                ('currency', models.CharField(editable=False, max_length=16, verbose_name='currency')),
                ('integration_id', models.TextField(editable=False, verbose_name='integration id')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('amount', models.PositiveIntegerField(editable=False, verbose_name='amount')),
                ('currency', models.CharField(editable=False, max_length=16, verbose_name='currency')),
                ('charge', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='rest_payments.Charge', verbose_name='refund')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
